---

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "/opt/academy-{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ academy_names }}"


# tasks file for create-dir-role
