---


- name: Copy file1
  ansible.builtin.copy:
    src: "files/{{ item }}-file1"
    dest: "/opt/academy-{{ item }}/{{ item }}-file1"
    mode: "0644"
  loop: "{{ file_names }}"

- name: Copy file2
  ansible.builtin.copy:
    src: "files/{{ item }}-file2"
    dest: "/opt/academy-{{ item }}/{{ item }}-file2"
    mode: "0644"
  loop: "{{ file_names }}"



# tasks file for copy-file-role
